[tool.poetry]
name = "peek"
version = "0.1.0"
description = "Peek at a Python object's direct and nested attributes."
authors = ["morefigs"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
